language: cpp

sudo: not required

matrix:      
   include:   
      - os: linux
        compiler: gcc
      - os: osx
        compiler: clang
        
script:
  - mkdir build
  - cd build  
  - cmake ..
  - make install
        