  /// \file Block.cc
/*
 *
 * Block.cc source template automatically generated by a class generator
 * Creation date : lun. janv. 18 2016
 *
 * This file is part of xdrstream libraries.
 * 
 * xdrstream is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * xdrstream is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with xdrstream.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "xdrstream/Block.h"
#include "xdrstream/XdrStream.h"

namespace xdrstream
{

Block::Block(XdrStream *pXdrStream, const std::string &name) :
		m_pXdrStream(pXdrStream),
		m_name(name)
{
	m_pXdrStream->addBlock(this);
}

//----------------------------------------------------------------------------------------------------

Block::~Block()
{
	m_pXdrStream->removeBlock(this);
}

//----------------------------------------------------------------------------------------------------

const std::string &Block::getName() const
{
	return m_name;
}

//----------------------------------------------------------------------------------------------------

const XdrStream *Block::getXdrStream() const
{
	return m_pXdrStream;
}

} 

