  /// \file xdrstream.h
/*
 *
 * xdrstream.h header template automatically generated by a class generator
 * Creation date : lun. f�vr. 8 2016
 *
 * This file is part of xdrstream libraries.
 * 
 * xdrstream is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * xdrstream is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with xdrstream.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author rete
 */


#ifndef XDR_MAIN_INCLUDE_H
#define XDR_MAIN_INCLUDE_H

// main definitions
#include "xdrstream/XdrDefinitions.h"

// xdrstream api
#include "xdrstream/XdrStreamInterface.h"
#include "xdrstream/IODevice.h"
#include "xdrstream/BufferDevice.h"
#include "xdrstream/FileDevice.h"
#include "xdrstream/Record.h"
#include "xdrstream/Block.h"
#include "xdrstream/Streamable.h"

#endif  //  XDRDEFINITIONS_H
